<?php

namespace App\OurEdu\ResourceSubjectFormats\Models\TrueFalse;

use App\OurEdu\BaseApp\BaseModel;
use App\OurEdu\Exams\Models\PrepareExamQuestion;
use App\OurEdu\GeneralExams\Models\PreparedGeneralExamQuestion;
use App\OurEdu\Options\Option;
use App\OurEdu\ResourceSubjectFormats\Models\QuestionHeadInterface;
use App\OurEdu\ResourceSubjectFormats\Models\ResourceSubjectFormatSubject;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class TrueFalseData extends BaseModel implements QuestionHeadInterface
{
    use HasFactory;

    protected $table = 'res_true_false_data';

    protected $fillable = [
        'description',
        'resource_subject_format_subject_id',
        'true_false_type',
        'question_type',
    ];

    /**
     * Bootstrap the model and its traits.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function (self $trueFalseData) {
            $questions = $trueFalseData->questions()->get();
            foreach ($questions as $question) {
                $question->delete();
            }
        });
    }

    public function resourceSubjectFormatSubject()
    {
        return $this->belongsTo(ResourceSubjectFormatSubject::class, 'resource_subject_format_subject_id');
    }

    public function questions()
    {
        return $this->hasMany(TrueFalseQuestion::class, 'res_true_false_data_id');
    }

    public function TrueFalseType()
    {
        return $this->belongsTo(Option::class, 'true_false_type');
    }

    public function optionType()
    {
        return $this->TrueFalseType();
    }

    /**
     * @return $this
     */
    public function questionHead()
    {
        return $this;
    }

    public function questionBank()
    {
        return $this->questions()->first()->questionBank();
    }
}
